info:
    title: BlogPost API
    description: API Documentation for BlogPost API
    version: 1.0.0
openapi: 3.0.1
components:
    schemas:
        Key:
            description: API Key
            type: string
            example: blog-xxxxx
        Token:
            description: Token
            type: string
            example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        Post:
            description: Blog Post
            type: object
            properties:
                postId:
                    type: string
                    example: xxxxx
                title:
                    type: string
                    example: Bla bla
                content:
                    type: string
                    example: Bla bla bla bla bla
                userId:
                    type: string
                    example: xxxxx
                author:
                    type: string
                    example: jespernyberg
        PostBody:
            description: Blog Post body
            type: object
            properties:
                title:
                    type: string
                    example: Bla bla
                content:
                    type: string
                    example: Bla bla bla bla bla
        UserBody:
            description: User body
            type: object
            properties:
                username:
                    type: string
                    example: jespernyberg
                password:
                    type: string
                    example: superhemligt123
    responses:
        BadRequestResponse:
            description: Bad request from client
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            success:
                                type: boolean
                                example: false
                            message:
                                type: string
                                example: Missing or invalid request parameters
        UnauthorizedResponse:
            description: Unauthorized request
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            success:
                                type: boolean
                                example: false
                            message:
                                type: string
                                example: Missing or invalid token
        ForbiddenResponse:
            description: Forbidden to perform requested action
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            success:
                                type: boolean
                                example: false
                            message:
                                type: string
                                example: User not authorized to perform action
        NotFoundResponse:
            description: Resource not found
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            success:
                                type: boolean
                                example: false
                            message:
                                type: string
                                example: The requested resource/s was not found
paths:
    /api/keys:
        get:
            tags:
                - API Key
            description: Returns a random API key
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            success:
                                type: boolean
                                example: true
                            key:
                                type: string
                                example: blog-xxxxx
            responses:
                "200":
                    description: Returns a random API key
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: true
                                    key:
                                        type: string
                                        example: blog-xxxxx
                "404":
                    $ref: "#/components/responses/NotFoundResponse"
    /api/auth/register:
        post:
            tags:
                - Auth
            description: Register new user
            parameters:
                - in: headers
                  name: x-api-key
                  required: true
                  schema:
                      type: object
                      $ref: "#/components/schemas/Key"
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: "#/components/schemas/UserBody"
            responses:
                "201":
                    description: Response for successful registration
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: true
                                    message:
                                        type: string
                                        example: User registered successfully
                "400":
                    $ref: "#/components/responses/BadRequestResponse"
                "401":
                    $ref: "#/components/responses/UnauthorizedResponse"
    /api/auth/login:
        post:
            tags:
                - Auth
            description: Login user
            parameters:
                - in: headers
                  name: x-api-key
                  required: true
                  schema:
                      type: object
                      $ref: "#/components/schemas/Key"
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: "#/components/schemas/UserBody"
            responses:
                "200":
                    description: Response for successful login
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: true
                                    message:
                                        type: string
                                        example: User logged in successfully
                                    token:
                                        type: string
                                        example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                "400":
                    $ref: "#/components/responses/BadRequestResponse"
                "401":
                    $ref: "#/components/responses/UnauthorizedResponse"
    /api/posts:
        get:
            tags:
                - Post
            description: Returns all posts
            parameters:
                - in: headers
                  name: x-api-key
                  required: true
                  schema:
                      type: object
                      $ref: "#/components/schemas/Key"
                - in: headers
                  name: Authorization
                  required: true
                  schema:
                      type: object
                      $ref: "#/components/schemas/Token"
            responses:
                "200":
                    description: Response containing all posts
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: true
                                    posts:
                                        type: array
                                        items:
                                            anyOf:
                                                - $ref: "#/components/schemas/Post"
                                                - $ref: "#/components/schemas/Post"
                                                - $ref: "#/components/schemas/Post"
                "401":
                    $ref: "#/components/responses/UnauthorizedResponse"
                "404":
                    $ref: "#/components/responses/NotFoundResponse"
        post:
            tags:
                - Post
            description: Add new post
            parameters:
                - in: headers
                  name: x-api-key
                  required: true
                  schema:
                      type: object
                      $ref: "#/components/schemas/Key"
                - in: headers
                  name: Authorization
                  required: true
                  schema:
                      type: object
                      $ref: "#/components/schemas/Token"
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: "#/components/schemas/PostBody"
            responses:
                "201":
                    description: Response for successfully creating new post
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: true
                                    message:
                                        type: string
                                        example: New post added successfully
                                    post:
                                        type: object
                                        $ref: "#/components/schemas/Post"
                "400":
                    $ref: "#/components/responses/BadRequestResponse"
                "401":
                    $ref: "#/components/responses/UnauthorizedResponse"
    /api/posts/{userId}:
        get:
            tags:
                - Post
            description: Returns all posts from specific user
            parameters:
                - in: headers
                  name: x-api-key
                  required: true
                  schema:
                      type: object
                      $ref: "#/components/schemas/Key"
                - in: headers
                  name: Authorization
                  required: true
                  schema:
                      type: object
                      $ref: "#/components/schemas/Token"
                - in: path
                  name: userId
                  required: true
                  schema:
                      type: string
                      example: xxxxx
            responses:
                "200":
                    description: Response containing all posts from specific user
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: true
                                    posts:
                                        type: array
                                        items:
                                            anyOf:
                                                - $ref: "#/components/schemas/Post"
                                                - $ref: "#/components/schemas/Post"
                                                - $ref: "#/components/schemas/Post"
                "400":
                    $ref: "#/components/responses/BadRequestResponse"
                "401":
                    $ref: "#/components/responses/UnauthorizedResponse"
                "404":
                    $ref: "#/components/responses/NotFoundResponse"
    /api/posts/{postId}:
        put:
            tags:
                - Post
            description:
            parameters:
                - in: headers
                  name: x-api-key
                  required: true
                  schema:
                      type: object
                      $ref: "#/components/schemas/Key"
                - in: headers
                  name: Authorization
                  required: true
                  schema:
                      type: object
                      $ref: "#/components/schemas/Token"
                - in: path
                  name: postId
                  required: true
                  schema:
                      type: string
                      example: xxxxx
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: "#/components/schemas/PostBody"
            responses:
                "200":
                    description: Response for successfully updating post
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: true
                                    message:
                                        type: string
                                        example: Post updated successfully
                                    post:
                                        type: object
                                        $ref: "#/components/schemas/Post"
                "400":
                    $ref: "#/components/responses/BadRequestResponse"
                "401":
                    $ref: "#/components/responses/UnauthorizedResponse"
                "403":
                    $ref: "#/components/responses/ForbiddenResponse"
        delete:
            tags:
                - Post
            description:
            parameters:
                - in: headers
                  name: x-api-key
                  required: true
                  schema:
                      type: object
                      $ref: "#/components/schemas/Key"
                - in: headers
                  name: Authorization
                  required: true
                  schema:
                      type: object
                      $ref: "#/components/schemas/Token"
                - in: path
                  name: postId
                  required: true
                  schema:
                      type: string
                      example: xxxxx
            responses:
                "200":
                    description: Response for successfully deleting post
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: true
                                    message:
                                        type: string
                                        example: Post deleted successfully
                                    post:
                                        type: object
                                        $ref: "#/components/schemas/Post"
                "400":
                    $ref: "#/components/responses/BadRequestResponse"
                "401":
                    $ref: "#/components/responses/UnauthorizedResponse"
                "403":
                    $ref: "#/components/responses/ForbiddenResponse"
